export const SET_SEARCH_NUMBER = 'SET_SEARCH_NUMBER';
export const REQUEST_SEARCH_BUS = 'REQUEST_SEARCH_BUS';
export const SEARCH_BUS_RESULT = 'SEARCH_BUS_RESULT';
export const SEARCH_BUS_FAILED = 'SEARCH_BUS_FAILED';

export const LOAD_STOPPOINT_STARTED = 'LOAD_STOPPOINT_STARTED';
export const LOAD_STOPPOINT_RESULT = 'LOAD_STOPPOINT_RESULT';
export const LOAD_STOPPOINT_FAILED = 'LOAD_STOPPOINT_FAILED';
